from .dataset_manager import DatasetManager

PAYLOAD = {
    'advanced': {
        'naughty_string': DatasetManager.load_key('advanced', 'naughty_string')
    },
    'ai': {
        "model_type": DatasetManager.load_key('ai', 'model_type'),
        "inference_result": DatasetManager.load_key('ai', 'inference_result'),
        "model_deployment_env": DatasetManager.load_key('ai', 'model_deployment_env'),
        "model_task": DatasetManager.load_key('ai', 'model_task'),
        "model_input_format": DatasetManager.load_key('ai', 'model_input_format'),
        "model_output_format": DatasetManager.load_key('ai', 'model_output_format'),
        "compute_precision": DatasetManager.load_key('ai', 'compute_precision'),
        "model_framework": DatasetManager.load_key('ai', 'model_framework'),
        "model_owner": DatasetManager.load_key('ai', 'model_owner'),
        "retraining_frequency": DatasetManager.load_key('ai', 'retraining_frequency'),
        "concept_drift_status": DatasetManager.load_key('ai', 'concept_drift_status'),
        "model_explainability_method": DatasetManager.load_key('ai', 'model_explainability_method'),
        "model_training_dataset": DatasetManager.load_key('ai', 'model_training_dataset'),
        "model_lifecycle_stage": DatasetManager.load_key('ai', 'model_lifecycle_stage'),
    },
    'basic':  {
        'frequency': DatasetManager.load_key('basic', 'frequency'),
        'nato_phonetic': DatasetManager.load_key('basic', 'nato_phonetic'),
        'emoji': DatasetManager.load_key('emoji', 'emoji'),
        'priority_levels': DatasetManager.load_key('basic', 'priority_levels'),
        'season':  DatasetManager.load_key('basic', 'season'),
        'sentiment': DatasetManager.load_key('basic', 'sentiment'),
        'weather_condition': DatasetManager.load_key('basic', 'weather_condition'),
        'weight_units': DatasetManager.load_key('basic', 'weight_units'),
        "height_units": DatasetManager.load_key('basic', 'height_units'),
        'day_of_week': DatasetManager.load_key('basic', 'day_of_week'),
        'duration_units': DatasetManager.load_key('basic', 'duration_units'),
        'metric_prefixes': DatasetManager.load_key('basic', 'metric_prefixes'),
        'imperial_units': DatasetManager.load_key('basic', 'imperial_units'),
        'month': DatasetManager.load_key('basic', 'month'),
        'paper_size': DatasetManager.load_key('basic', 'paper_size'),
        'punctuation_marks': DatasetManager.load_key('basic', 'punctuation_marks'),
    },
    'car': {
        "vehicle_type":  DatasetManager.load_key('car', 'vehicle_type'),
        "engine_type": DatasetManager.load_key('car', 'engine_type'),
        "fuel_type": DatasetManager.load_key('car', 'fuel_type'),
        "gas_type": DatasetManager.load_key('car', 'gas_type'),
        "transmission_type": DatasetManager.load_key('car', 'transmission_type'),
    },
    'commerce': {
        "product": {
            "category": DatasetManager.load_key('commerce', 'category'),
            "description": DatasetManager.load_key('commerce', 'description'),
            "grocery": DatasetManager.load_key('commerce', 'grocery'),
            'name': DatasetManager.load_key('commerce', 'name'),
            'subcategory': DatasetManager.load_key('commerce', 'subcategory'),
        },
        'stock': {
            'industries': DatasetManager.load_key('commerce', 'stock_industries'),
            'market': DatasetManager.load_key('commerce', 'stock_market')
        },
        'order_status': DatasetManager.load_key('commerce', 'order_status'),
        'payment_method': DatasetManager.load_key('commerce', 'payment_method'),
        'restaurant_type': DatasetManager.load_key('commerce', 'restaurant_type'),
        'review_text': DatasetManager.load_key('commerce', 'review_text'),
        'shipping_method': DatasetManager.load_key('commerce', 'shipping_method'),
        'subscription_plan': DatasetManager.load_key('commerce', 'subscription_plan'),
        'coffee_type': DatasetManager.load_key('commerce', 'coffee_type'),
        'delivery_status': DatasetManager.load_key('commerce', 'delivery_status'),
        'fabric_type': DatasetManager.load_key('commerce', 'fabric_type'),
        'furniture_type': DatasetManager.load_key('commerce', 'furniture_type'),
        'gem_stone': DatasetManager.load_key('commerce', 'gem_stone'),
        'ingredient': DatasetManager.load_key('commerce', 'ingredient'),
        'inventory_status': DatasetManager.load_key('commerce', 'inventory_status'),
        'loyalty_tier': DatasetManager.load_key('commerce', 'loyalty_tier'),
        'meal_type': DatasetManager.load_key('commerce', 'meal_type'),
        'membership_level': DatasetManager.load_key('commerce', 'membership_level'),
        'office_supply': DatasetManager.load_key('commerce', 'office_supply'),
        'payment_status': DatasetManager.load_key('commerce', 'payment_status'),
        'postal_service': DatasetManager.load_key('commerce', 'postal_service'),
        'recipe_name': DatasetManager.load_key('commerce', 'recipe_name'),
        'sales_channel': DatasetManager.load_key('commerce', 'sales_channel'),
        'warranty_period': DatasetManager.load_key('commerce', 'warranty_period'),
        'water_type': DatasetManager.load_key('commerce', 'water_type'),
        'return_reason': DatasetManager.load_key('commerce', 'return_reason'),
        'bundle_type': DatasetManager.load_key('commerce', 'bundle_type'),
        "price_sensitivity_level": DatasetManager.load_key('commerce', 'price_sensitivity_level'),
        "freight_mode": DatasetManager.load_key('commerce', 'freight_mode'),
        "recommendation_slot_position":  DatasetManager.load_key('commerce', 'recommendation_slot_position'),
    },
    'communication': {
        'latency_range': {
            "2G": (150, 1000),
            "2G EDGE": (200, 800),
            "3G": (100, 500),
            "3G HSPA": (80, 400),
            "4G LTE": (20, 100),
            "4G LTE-A": (15, 80),
            "5G": (5, 50),
            "5G NSA": (5, 40),
            "5G SA": (3, 20),
            "Wi-Fi 2.4GHz": (2, 60),
            "Wi-Fi 5GHz": (1, 30),
            "Wi-Fi 6": (1, 15),
            "Satellite": (500, 1500),
            "Satellite LEO": (50, 100),
            "DSL": (10, 100),
            "Fiber": (1, 20),
        },
        "bluetooth_version": DatasetManager.load_key('communication', 'bluetooth_version'),
        "upload_speed": DatasetManager.load_key('communication', 'upload_speed'),
        "download_speed": DatasetManager.load_key('communication', 'download_speed'),
        "sim_card_type": DatasetManager.load_key('communication', 'sim_card_type'),
        "mobile_carrier": DatasetManager.load_key('communication', 'mobile_carrier'),
        "data_plan": DatasetManager.load_key('communication', 'data_plan'),
        "wifi_standard": DatasetManager.load_key('communication', 'wifi_standard'),
        "wifi_band": DatasetManager.load_key('communication', 'wifi_band'),
        "nfc_support": DatasetManager.load_key('communication', 'nfc_support'),
        "hotspot_capability": DatasetManager.load_key('communication', 'hotspot_capability'),
        "roaming_status": DatasetManager.load_key('communication', 'roaming_status'),
        "carrier_lock_status": DatasetManager.load_key('communication', 'carrier_lock_status'),
        "volte_support": DatasetManager.load_key('communication', 'volte_support'),
        "wifi_calling_support": DatasetManager.load_key('communication', 'wifi_calling_support'),
        "dual_sim_capability": DatasetManager.load_key('communication', 'dual_sim_capability'),
        "apn_settings": DatasetManager.load_key('communication', 'apn_settings'),
        "call_quality_rating": DatasetManager.load_key('communication', 'call_quality_rating'),
    },
    'construction': {
        "heavy_equipment": DatasetManager.load_key('construction', 'heavy_equipment'),
        "materials":  DatasetManager.load_key('construction', 'materials'),
        "roles": DatasetManager.load_key('construction', 'roles'),
        "subcontracts": DatasetManager.load_key('construction', 'subcontracts'),
        'trades': DatasetManager.load_key('construction', 'trades'),
        "building_type": DatasetManager.load_key('construction', 'building_type'),
        "material_type": DatasetManager.load_key('construction', 'material_type'),
        "tool_type": DatasetManager.load_key('construction', 'tool_type'),
    },
    'crypto': {
        "wallet": DatasetManager.load_key('crypto', 'wallet')
    },
    'education': {
        "academic_subject": DatasetManager.load_key('education', 'academic_subject'),
        "attendance_status": DatasetManager.load_key('education', 'attendance_status'),
        "certification": DatasetManager.load_key('education', 'certification'),
        "college_major": DatasetManager.load_key('education', 'college_major'),
        "elearning_platform": DatasetManager.load_key('education', 'e_learning_platform'),
        "qualification": DatasetManager.load_key('education', 'qualification'),
        "school_type": DatasetManager.load_key('education', 'school_type'),
        "semester": DatasetManager.load_key('education', 'semester')
    },
    'finance': {
        "loan_type": DatasetManager.load_key('finance', 'loan_type'),
        "asset_type": DatasetManager.load_key('finance', 'asset_type'),
        "expense_category": DatasetManager.load_key('finance', 'expense_category'),
        "grant_type": DatasetManager.load_key('finance', 'grant_type'),
        "insurance_provider": DatasetManager.load_key('finance', 'insurance_provider'),
        "insurance_type": DatasetManager.load_key('finance', 'insurance_type'),
        "investment_strategy": DatasetManager.load_key('finance', 'investment_strategy'),
        "payment_term": DatasetManager.load_key('finance', 'payment_term'),
        "risk_level": DatasetManager.load_key('finance', 'risk_level'),
        "tax_type": DatasetManager.load_key('finance', 'tax_type'),
        "transaction_type": DatasetManager.load_key('finance', 'transaction_type'),
        "spending_behavior": DatasetManager.load_key('finance', 'spending_behavior'),
        "investment_persona": DatasetManager.load_key('finance', 'investment_persona'),
        "transaction_pattern": DatasetManager.load_key('finance', 'transaction_pattern'),
        "financial_goal": DatasetManager.load_key('finance', 'financial_goal'),
        "account_type": DatasetManager.load_key('finance', 'account_type'),
        "transfer_channel": DatasetManager.load_key('finance', 'transfer_channel'),
        "aml_risk_category": DatasetManager.load_key('finance', 'aml_risk_category'),
        "spending_category": DatasetManager.load_key('finance', 'spending_category'),
        "savings_goal": DatasetManager.load_key('finance', 'savings_goal'),
        "credit_score_band": DatasetManager.load_key('finance', 'credit_score_band'),
        "kyc_status": DatasetManager.load_key('finance', 'kyc_status'),
        "wealth_segment": DatasetManager.load_key('finance', 'wealth_segment'),
    },
    'gaming': {
        "badge": DatasetManager.load_key('gaming', 'badge'),
        "avatar_class": DatasetManager.load_key('gaming', 'avatar_class'),
        "skill_level": DatasetManager.load_key('gaming', 'skill_level'),
        "match_result": DatasetManager.load_key('gaming', 'match_result'),
        "player_role": DatasetManager.load_key('gaming', 'player_role'),
        "guild_name": DatasetManager.load_key('gaming', 'guild_name'),
        "achievement_title": DatasetManager.load_key('gaming', 'achievement_title'),
        "session_outcome": DatasetManager.load_key('gaming', 'session_outcome'),
    },
    'health': {
        "blood_type": DatasetManager.load_key('health', 'blood_type'),
        "disease_name": DatasetManager.load_key('health', 'disease_name'),
        "medication_dosage": DatasetManager.load_key('health', 'medication_dosage'),
        "vitamin": DatasetManager.load_key('health', 'vitamin'),
        "allergy": DatasetManager.load_key('health', 'allergy'),
        "body_part": DatasetManager.load_key('health', 'body_part'),
        "chromosome": DatasetManager.load_key('health', 'chromosome'),
        "dietary_restriction": DatasetManager.load_key('health', 'dietary_restriction'),
        "disability_type": DatasetManager.load_key('health', 'disability_type'),
        "emergency_type": DatasetManager.load_key('health', 'emergency_type'),
        "exercise_type": DatasetManager.load_key('health', 'exercise_type'),
        "health_insurance_plan": DatasetManager.load_key('health', 'health_insurance_plan'),
        "hormone":  DatasetManager.load_key('health', 'hormone'),
        "hospital_department": DatasetManager.load_key('health', 'hospital_department'),
        "lab_test": DatasetManager.load_key('health', 'lab_test'),
        "macro_nutrient": DatasetManager.load_key('health', 'macro_nutrient'),
        "medical_specialty": DatasetManager.load_key('health', 'medical_specialty'),
        "mental_health_condition": DatasetManager.load_key('health', 'mental_health_condition'),
        "nutrient": DatasetManager.load_key('health', 'nutrient'),
        "organ":  DatasetManager.load_key('health', 'organ'),
        "pharmacy_name": DatasetManager.load_key('health', 'pharmacy_name'),
        "symptom": DatasetManager.load_key('health', 'symptom'),
        "workout_duration": ("15 minutes", "30 minutes", "45 minutes", "90 minutes", "1 hour", "2 hour", "3 Hour"),
        "vaccination_type": DatasetManager.load_key('health', 'vaccination_type'),
        "diet_type": DatasetManager.load_key('health', 'diet_type'),
        "blood_pressure_category": DatasetManager.load_key('health', 'blood_pressure_category'),
        "allergy_flag": DatasetManager.load_key('health', 'allergy_flag'),
        "appointment_status": DatasetManager.load_key('health', 'appointment_status'),
        "lab_test_type": DatasetManager.load_key('health', 'lab_test_type'),
        "triage_level": DatasetManager.load_key('health', 'triage_level'),
    },
    'it': {
        'domains': DatasetManager.load_key('it', 'domains'),
        'mime_types': {
            "application": ("application/atom+xml", "application/ecmascript", "application/EDI-X12", "application/EDIFACT", "application/json", "application/javascript",
                            "application/octet-stream", "application/ogg", "application/pdf", "application/postscript", "application/rdf+xml", "application/rss+xml",
                            "application/soap+xml", "application/font-woff", "application/xhtml+xml", "application/xml-dtd", "application/xop+xml", "application/zip", "application/gzip"),
            "audio": ("audio/basic", "audio/L24", "audio/mp4", "audio/mpeg", "audio/ogg", "audio/vorbis", "audio/vnd.rn-realaudio", "audio/vnd.wave", "audio/webm"),
            "image": ("image/gif", "image/jpeg", "image/pjpeg", "image/png", "image/svg+xml", "image/tiff", "image/vnd.microsoft.icon"),
            "message": ("message/http", "message/imdn+xml", "message/partial", "message/rfc822"),
            "model": ("model/example", "model/iges", "model/mesh", "model/vrml", "model/x3d+binary", "model/x3d+vrml", "model/x3d+xml"),
            "multipart": ("multipart/mixed", "multipart/alternative", "multipart/related", "multipart/form-data", "multipart/signed", "multipart/encrypted"),
            "text": ("text/cmd", "text/css", "text/csv", "text/html", "text/javascript", "text/plain", "text/vcard", "text/xml"),
            "video": ("video/mpeg", "video/mp4", "video/ogg", "video/quicktime", "video/webm", "video/x-matroska", "video/x-ms-wmv", "video/x-flv"),
        },
        'user_agents': DatasetManager.load_key('it', 'user_agents'),
        'tlds': (".com", ".org", ".net", ".io", ".co", ".edu", ".gov", ".mil", ".us", ".uk", ".ca", ".au", ".de", ".fr", ".jp", ".sg", ".ph", ".in", ".cn", ".br",
                         ".za", ".es", ".it", ".nl", ".se", ".no", ".ch", ".biz", ".info", ".xyz", ".online", ".site", ".tech", ".store", ".ai", ".app", ".dev", ".cloud", ".me", ".tv"),
        'prefix': ("sk-", "api_", "key-", "ghp_", "tok_", "auth_"),
        'browsers': (("Google Chrome", "130.0.6723.69"),
                     ("Mozilla Firefox", "132.0"),
                     ("Microsoft Edge", "130.0.2849.56"),
                     ("Safari", "18.0"),
                     ("Opera", "105.0.4985.64"),
                     ("Brave", "1.73.113"),
                     ("Vivaldi", "6.7.3329.25"),
                     ("Samsung Internet", "25.0.1.3"),
                     ("UC Browser", "15.1.0.1225"),
                     ("DuckDuckGo Browser", "1.100.2"),
                     ("Tor Browser", "13.0.4"),
                     ("QQ Browser", "15.2.0.0"),
                     ("Yandex Browser", "24.9.1.822"),
                     ("Puffin Browser", "9.10.2.51548"),
                     ("Maxthon", "7.1.8.9000")),
        'cloud_provider': DatasetManager.load_key('it', 'cloud_provider'),
        'database_type': DatasetManager.load_key('it', 'database_type'),
        'cloud_storage_service': DatasetManager.load_key('it', 'cloud_storage_service'),
        'docker_images': DatasetManager.load_key('it', 'docker_images'),
        'error_messages': DatasetManager.load_key('it', 'error_messages'),
        'file_size_units': ("B", "KB", "MB", "GB", "TB"),
        'font_family': DatasetManager.load_key('it', 'font_family'),
        'http_method': ("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"),
        'http_standard_code': DatasetManager.load_key('it', 'http_standard_code'),
        'iot_device_type': DatasetManager.load_key('it', 'iot_device_type'),
        'operating_system': DatasetManager.load_key('it', 'operating_system'),
        'port_number': DatasetManager.load_key('it', 'port_number'),
        'programming_language': DatasetManager.load_key('it', 'programming_language'),
        'security_question': DatasetManager.load_key('it', 'security_question'),
        "wifi_ssid": DatasetManager.load_key('it', 'wifi_ssid'),
        "app_store_category": DatasetManager.load_key('it', 'app_store_category'),
        "cookie_name": DatasetManager.load_key('it', 'cookie_name'),
        'css_color': DatasetManager.load_key('it', 'css_color'),
        'data_centers': DatasetManager.load_key('it', 'data_centers'),
        'dns_record_type': DatasetManager.load_key('it', 'dns_record_type'),
        'document_type': DatasetManager.load_key('it', 'document_type'),
        'electrical_component': DatasetManager.load_key('it', 'electrical_component'),
        'encryption_algorithm': DatasetManager.load_key('it', 'encryption_algorithm'),
        'form_factor': DatasetManager.load_key('it', 'form_factor'),
        'framework': DatasetManager.load_key('it', 'framework'),
        'hardware':  DatasetManager.load_key('it', 'hardware'),
        'incident_type': DatasetManager.load_key('it', 'incident_type'),
        'keyboard_layout': DatasetManager.load_key('it', 'keyboard_layout'),
        'laptop_brand':  DatasetManager.load_key('it', 'laptop_brand'),
        'license_type': DatasetManager.load_key('it', 'license_type'),
        'memory_size':  DatasetManager.load_key('it', 'memory_size'),
        'microservice_name':  DatasetManager.load_key('it', 'microservice_name'),
        'network_protocol': DatasetManager.load_key('it', 'network_protocol'),
        'notification_type': DatasetManager.load_key('it', 'notification_type'),
        'package_manager': DatasetManager.load_key('it', 'package_manager'),
        'password_strength': DatasetManager.load_key('it', 'password_strength'),
        'permission_level': DatasetManager.load_key('it', 'permission_level'),
        'power_source': DatasetManager.load_key('it', 'power_source'),
        'printer_type': DatasetManager.load_key('it', 'printer_type'),
        'protocol_version': DatasetManager.load_key('it', 'protocol_version'),
        'screen_resolution': DatasetManager.load_key('it', 'screen_resolution'),
        "screen_size": DatasetManager.load_key('it', 'screen_size'),
        "social_media_platform": DatasetManager.load_key('it', 'social_media_platform'),
        "software_license": DatasetManager.load_key('it', 'software_license'),
        "storage_type": DatasetManager.load_key('it', 'storage_type'),
        "subject_line": DatasetManager.load_key('it', 'subject_line'),
        "technology_stack": DatasetManager.load_key('it', 'technology_stack'),
        "ticket_priority": DatasetManager.load_key('it', 'ticket_priority'),
        "uptime_percentage": DatasetManager.load_key('it', 'uptime_percentage'),
        "api_endpoint_path": DatasetManager.load_key('it', 'api_endpoint_path'),
        "log_level": DatasetManager.load_key('it', 'log_level'),
        "server_name": DatasetManager.load_key('it', 'server_name'),
        "sensor_type":  DatasetManager.load_key('it', 'sensor_type'),
        "device_location":  DatasetManager.load_key('it', 'device_location'),
        "power_state":  DatasetManager.load_key('it', 'power_state'),
        "smart_device_brand": DatasetManager.load_key('it', 'smart_device_brand'),
        "smart_device_type":  DatasetManager.load_key('it', 'smart_device_type'),
        "automation_trigger":  DatasetManager.load_key('it', 'automation_trigger'),
        "automation_action":  DatasetManager.load_key('it', 'automation_action'),
        "energy_mode":  DatasetManager.load_key('it', 'energy_mode'),
        "feature_usage_event":  DatasetManager.load_key('it', 'feature_usage_event'),
        "subscription_renewal_status": DatasetManager.load_key('it', 'subscription_renewal_status'),
        "engagement_level": DatasetManager.load_key('it', 'engagement_level'),

    },
    'legal': {
        'crime': DatasetManager.load_key('legal', 'crime'),
        "law_type": DatasetManager.load_key('legal', 'law_type'),
        "court_level": DatasetManager.load_key('legal', 'court_level'),
        "legislation_status": DatasetManager.load_key('legal', 'legislation_status'),
        "legal_jurisdiction": DatasetManager.load_key('legal', 'legal_jurisdiction'),
        "evidence_type": DatasetManager.load_key('legal', 'evidence_type'),
        "legal_representation": DatasetManager.load_key('legal', 'legal_representation'),
        "verdict": DatasetManager.load_key('legal', 'verdict'),
        "penalty_type": DatasetManager.load_key('legal', 'penalty_type'),
        "appeal_status": DatasetManager.load_key('legal', 'appeal_status'),
        "contract_type": DatasetManager.load_key('legal', 'contract_type'),
        "notary_status": DatasetManager.load_key('legal', 'notary_status'),
        "legal_compliance_status": DatasetManager.load_key('legal', 'legal_compliance_status'),
        "regulatory_agency": DatasetManager.load_key('legal', 'regulatory_agency'),
        "legal_filing_type": DatasetManager.load_key('legal', 'legal_filing_type'),
        "legal_fee_category": DatasetManager.load_key('legal', 'legal_fee_category'),
        "bail_status": DatasetManager.load_key('legal', 'bail_status'),
    },
    'location': {
        "timezone_abbreviation": DatasetManager.load_key('location', 'timezone_abbreviation'),
        "compass_direction": DatasetManager.load_key('location', 'compass_direction'),
        "continent": DatasetManager.load_key('location', 'continent'),
        "facility_type": DatasetManager.load_key('location', 'facility_type'),
        "federal_holiday": DatasetManager.load_key('location', 'federal_holiday'),
        "floor_number": DatasetManager.load_key('location', 'floor_number'),
        "holiday": DatasetManager.load_key('location', 'holiday'),
        "home_type": DatasetManager.load_key('location', 'home_type'),
        "property_type": DatasetManager.load_key('location', 'property_type'),
        "road_type": DatasetManager.load_key('location', 'road_type'),
        "venue_type": DatasetManager.load_key('location', 'venue_type'),
        "geo_zone": DatasetManager.load_key('location', 'venue_type'),
        "street_type": DatasetManager.load_key('location', 'street_type'),
        "traffic_flow_level": DatasetManager.load_key('location', 'traffic_flow_level'),
        "urban_land_use": DatasetManager.load_key('location', 'urban_land_use'),
        "public_service_request_type": DatasetManager.load_key('location', 'public_service_request_type'),
    },
    'marketing': {
        'campaign_name': DatasetManager.load_key('marketing', 'campaign_name'),
        "recommendation_reason": DatasetManager.load_key('marketing', 'recommendation_reason'),
        "next_best_action":  DatasetManager.load_key('marketing', 'next_best_action'),
        "user_preference_tag": DatasetManager.load_key('marketing', 'user_preference_tag'),
        "promotion_type":  DatasetManager.load_key('marketing', 'promotion_type'),
        "customer_segment":  DatasetManager.load_key('marketing', 'customer_segment'),
        "channel_source":  DatasetManager.load_key('marketing', 'channel_source'),
        "conversion_status": DatasetManager.load_key('marketing', 'conversion_status'),
        "churn_risk":  DatasetManager.load_key('marketing', 'churn_risk'),
        "preferred_communication_channel": DatasetManager.load_key('marketing', 'preferred_communication_channel'),
        "recent_search_term":  DatasetManager.load_key('marketing', 'recent_search_term'),
        "cart_abandonment_status":  DatasetManager.load_key('marketing', 'cart_abandonment_status'),
        "cross_sell_opportunity": DatasetManager.load_key('marketing', 'cross_sell_opportunity'),
        "upsell_opportunity": DatasetManager.load_key('marketing', 'upsell_opportunity'),
        "sms_response_status": DatasetManager.load_key('marketing', 'sms_response_status'),
        "coupon_usage_status": DatasetManager.load_key('marketing', 'coupon_usage_status'),
        "referral_source":  DatasetManager.load_key('marketing', 'referral_source'),
        "influencer_attribution": DatasetManager.load_key('marketing', 'influencer_attribution'),
        "preferred_product_category":  DatasetManager.load_key('marketing', 'preferred_product_category'),
        "seasonal_interest":  DatasetManager.load_key('marketing', 'seasonal_interest'),
        "price_sensitivity":  DatasetManager.load_key('marketing', 'price_sensitivity'),
        "customer_mood_intent": DatasetManager.load_key('marketing', 'customer_mood_intent'),
    },
    'nature': {
        "planet": DatasetManager.load_key('nature', 'planet'),
        "biome": DatasetManager.load_key('nature', 'biome'),
        "bird_species": DatasetManager.load_key('nature', 'bird_species'),
        "constellation":  DatasetManager.load_key('nature', 'constellation'),
        "dog_breed":  DatasetManager.load_key('nature', 'dog_breed'),
        "ecosystem":  DatasetManager.load_key('nature', 'ecosystem'),
        "element_state": DatasetManager.load_key('nature', 'element_state'),
        "energy_source":  DatasetManager.load_key('nature', 'energy_source'),
        "environmental_issue":  DatasetManager.load_key('nature', 'environmental_issue'),
        "fish_species": DatasetManager.load_key('nature', 'fish_species'),
        "flower_type":  DatasetManager.load_key('nature', 'flower_type'),
        "insect_species": DatasetManager.load_key('nature', 'insect_species'),
        "moon_phase":  DatasetManager.load_key('nature', 'moon_phase'),
        "ocean": DatasetManager.load_key('nature', 'ocean'),
        "particle":  DatasetManager.load_key('nature', 'particle'),
        "precipitation_type":  DatasetManager.load_key('nature', 'precipitation_type'),
        "satellite": DatasetManager.load_key('nature', 'satellite'),
        "species":  DatasetManager.load_key('nature', 'species'),
        "tree_species": DatasetManager.load_key('nature', 'tree_species'),
        "wind_direction": DatasetManager.load_key('nature', 'wind_direction'),
        "animal_habitat": DatasetManager.load_key('nature', 'animal_habitat'),
        "geological_formation": DatasetManager.load_key('nature', 'geological_formation'),
        "climate_zone": DatasetManager.load_key('nature', 'climate_zone'),
        "natural_resource":  DatasetManager.load_key('nature', 'natural_resource'),
        "vegetation_type": DatasetManager.load_key('nature', 'vegetation_type'),
        'hazard_risk_zone': DatasetManager.load_key('nature', 'hazard_risk_zone'),
        'air_quality_category': DatasetManager.load_key('nature', 'air_quality_category'),
    },
    'personal': {
        'race': DatasetManager.load_key('personal', 'race'),
        'gender': {
            'facebook': DatasetManager.load_key('personal', 'gender_facebook'),
            'main': ('Male', 'Female', 'Non-binary', 'Genderqueer', 'Genderfluid', 'Bigender', 'Agender'),
            'abbrev': ('M', 'F'),
            'binary': ('Male', 'Female')
        },
        'job':  DatasetManager.load_key('misc', 'job'),
        'shirt_sizes': ("XS", "S", "M", "L", "XL", "XXL", "XXXL"),
        'buzzword': DatasetManager.load_key('personal', 'buzzword'),
        'nationality': DatasetManager.load_key('personal', 'nationality'),
        'quote': DatasetManager.load_key('quote', 'quotes'),
        "business_type": DatasetManager.load_key('personal', 'business_type'),
        "degree": DatasetManager.load_key('personal', 'degree'),
        "education_level": DatasetManager.load_key('personal', 'education_level'),
        "employment_status": DatasetManager.load_key('personal', 'employment_status'),
        "hobby":  DatasetManager.load_key('personal', 'hobby'),
        "industry": DatasetManager.load_key('personal', 'industry'),
        "marital_status": DatasetManager.load_key('personal', 'marital_status'),
        "military_rank": DatasetManager.load_key('personal', 'military_rank'),
        "mood":  DatasetManager.load_key('personal', 'mood'),
        "pronoun": DatasetManager.load_key('personal', 'pronoun'),
        "religion": DatasetManager.load_key('personal', 'religion'),
        "team_name": DatasetManager.load_key('personal', 'team_name'),
        "zodiac_sign": DatasetManager.load_key('personal', 'zodiac_sign'),
        "age_group": DatasetManager.load_key('personal', 'age_group'),
        "conference_name": DatasetManager.load_key('personal', 'conference_name'),
        "contract_type":  DatasetManager.load_key('personal', 'contract_type'),
        "event_type":  DatasetManager.load_key('personal', 'event_type'),
        "hair_color":  DatasetManager.load_key('personal', 'hair_color'),
        "income_level":  DatasetManager.load_key('personal', 'income_level'),
        "interview_stage": DatasetManager.load_key('personal', 'interview_stage'),
        "legal_entity": DatasetManager.load_key('personal', 'legal_entity'),
        "life_stage": DatasetManager.load_key('personal', 'life_stage'),
        "occupation": DatasetManager.load_key('misc', 'job'),
        "organization_type": DatasetManager.load_key('personal', 'organization_type'),
        "performance_rating":  DatasetManager.load_key('personal', 'performance_rating'),
        "pet_type": DatasetManager.load_key('personal', 'pet_type'),
        "political_party": DatasetManager.load_key('personal', 'political_party'),
        "project_status":  DatasetManager.load_key('personal', 'project_status'),
        "reaction": DatasetManager.load_key('personal', 'reaction'),
        "relationship_type": DatasetManager.load_key('personal', 'relationship_type'),
        "role": DatasetManager.load_key('personal', 'role'),
        "daily_habit": DatasetManager.load_key('personal', 'daily_habit'),
        "personality_trait":  DatasetManager.load_key('personal', 'personality_trait'),
    },
    'political': {
        'election_type': DatasetManager.load_key('political', 'election_Type'),
        "political_ideology": DatasetManager.load_key('political', 'political_ideology'),
        "political_party": DatasetManager.load_key('political', 'political_party'),
        "party_affiliation_strength": DatasetManager.load_key('political', 'party_affiliation_strength'),
        "government_branch": DatasetManager.load_key('political', 'government_branch'),
        "head_of_state": DatasetManager.load_key('political', 'head_of_state'),
        "head_of_government": DatasetManager.load_key('political', 'head_of_government'),
        "cabinet_position": DatasetManager.load_key('political', 'cabinet_position'),
        "voter_eligibility": DatasetManager.load_key('political', 'voter_eligibility'),
        "campaign_funding_source": DatasetManager.load_key('political', 'campaign_funding_source'),
        "lobbying_influence_level": DatasetManager.load_key('political', 'lobbying_influence_level'),
        "policy_domain": DatasetManager.load_key('political', 'policy_domain'),
        "diplomatic_relationship": DatasetManager.load_key('political', 'diplomatic_relationship'),
        "treaty_type": DatasetManager.load_key('political', 'treaty_type'),
        "sanction_type": DatasetManager.load_key('political', 'sanction_type'),
        "border_control_status": DatasetManager.load_key('political', 'border_control_status'),
        "military_alliance": DatasetManager.load_key('political', 'military_alliance'),
        "geopolitical_region": DatasetManager.load_key('political', 'geopolitical_region'),
    },
    'products': {
        "podcast_name": DatasetManager.load_key('products', 'podcast_name'),
        "streaming_service": DatasetManager.load_key('products', 'streaming_service'),
        "award_name": DatasetManager.load_key('products', 'award_name'),
        "broadcast_network": DatasetManager.load_key('products', 'broadcast_network'),
        "content_rating": DatasetManager.load_key('products', 'content_rating'),
        "guitar_type": DatasetManager.load_key('products', 'guitar_type'),
        "magazine_title": DatasetManager.load_key('products', 'magazine_title'),
        "media_format": DatasetManager.load_key('products', 'media_format'),
        "musical_genre": DatasetManager.load_key('products', 'musical_genre'),
        "musical_instrument": DatasetManager.load_key('products', 'musical_instrument'),
        "news_category": DatasetManager.load_key('products', 'news_category'),
        "parental_rating": DatasetManager.load_key('products', 'parental_rating'),
        "record_label": DatasetManager.load_key('products', 'record_label'),
        "sound_effect": DatasetManager.load_key('products', 'sound_effect'),
        "supernatural_creature": DatasetManager.load_key('products', 'supernatural_creature'),
        "video_format": DatasetManager.load_key('products', 'video_format'),
        "video_quality": DatasetManager.load_key('products', 'video_quality'),
        "stock_reorder_flag": DatasetManager.load_key('products', 'stock_reorder_flag'),
        "shelf_location": DatasetManager.load_key('products', 'shelf_location'),
        "product_grade": DatasetManager.load_key('products', 'product_grade'),
        "demand_forecast": DatasetManager.load_key('products', 'demand_forecast'),
        "supplier_contract": DatasetManager.load_key('products', 'supplier_contract'),
    },
    'sports': {
        'olympic': DatasetManager.load_key('sports', 'olympic'),
        "equipment_type": DatasetManager.load_key('sports', 'equipment_type'),
        "league": DatasetManager.load_key('sports', 'league'),
        "stadium_name": DatasetManager.load_key('sports', 'stadium_name'),
    },
    'travel': {
        "flight_status": DatasetManager.load_key('travel', 'flight_status'),
        "room_type": DatasetManager.load_key('travel', 'room_type'),
        "amenity": DatasetManager.load_key('travel', 'amenity'),
        "bed_size": DatasetManager.load_key('travel', 'bed_size'),
        "parking_type": DatasetManager.load_key('travel', 'parking_type'),
        "ticket_type": DatasetManager.load_key('travel', 'ticket_type'),
        "transport_mode": DatasetManager.load_key('travel', 'transport_mode'),
    },


    'departments': {
        'corporate':  DatasetManager.load_key('misc', 'corporate'),
        'retail': DatasetManager.load_key('misc', 'retail'),
    },
    'file': {
        "image":  DatasetManager.load_key('file', 'image'),
        "audio": DatasetManager.load_key('file', 'audio'),
        "video": DatasetManager.load_key('file', 'video'),
        "text": DatasetManager.load_key('file', 'text'),
        "office": DatasetManager.load_key('file', 'office'),
        "archive": DatasetManager.load_key('file', 'archive'),
        "executable": DatasetManager.load_key('file', 'executable'),
        "data": DatasetManager.load_key('file', 'data'),
        "code": DatasetManager.load_key('file', 'code'),
        "font": DatasetManager.load_key('file', 'font'),
        "system": DatasetManager.load_key('file', 'system'),
        "design": DatasetManager.load_key('file', 'design'),
        "backup": DatasetManager.load_key('file', 'backup'),
    },
    'format': {
        'company': ("{{last_name}} {{company_suffix}}", "{{last_name}}-{{last_name}}", "{{last_name}}, {{last_name}} and {{last_name}}",),
        'username':  ("{{first_name}}.{{last_name}}", "{{last_name}}.{{first_name}}", "{{first_name}}_{{last_name}}",
                      "{{first_name}}-{{last_name}}", "{{first_name}}{{last_name}}", "{{first_name}}.{{last_name}}@",
                      "{{first_name}}.{{last_name}}##", "{{first_name}}_{{last_name}}@", "{{first_name}}_{{last_name}}_##",
                      "{{first_name}}##",  "{{last_name}}##",  "@{{first_name}}_{{last_name}}",  "{{first_name}}_@{{last_name}}",
                      "{{first_name}}##@{{last_name}}",  "{{first_name}}_{{last_name}}_@", "{{first_name}}-{{last_name}}##",
                      "{{first_name}}.{{last_name}}_@", "{{first_name}}##.{{last_name}}", "{{last_name}}_{{first_name}}##"),
        'email': "{{user_name}}@{{domain_name}}",
        'plate_number': ("#^^####", "##^^###", "### ^^^", "####", "^^^####", "### ^^^", "###^^^", "#^^^###",
                         "###-^^^", "^^^-###", "###-^^^", "######", "^^-####", "^^^ ^##", "### ^^^", "^## #^^",
                         "### #^^", "^^^####", "^^ ####", "^^^ ###", "H^^ ###", "Z^^ ###", "K^^ ###", "L^^ ###",
                         "M^^ ###", "^ ######", "#^ #####", "#^ ^####", "#^ ^^^###", "#^ ####^", "##^ ####",
                         "^^ #####", "^^# ####", "###^", "###^^", "###^^^", "^^^ ###", "### ^^^", "### ^^^",
                         "### ^^^", "#### ^^", "#^^####", "#^^^ ##", "#^^ ###", "### ^^#", "##^ ^##", "### ^^^",
                         "#^^ ^##", "###-^^^", "^^^ ###", "^^# ^#^", "#-#####^", "##-####^", "^^^ ###", "#-^####",
                         "##-^###", "##-^^##", "##^-###", "### ####", "^##-^^^", "###-^^^", "^^^-###", "^^^-####",
                         "###-^^^^", "### ^^^", "^^^ ###", "^^^ ####", "^^^-###", "### ^^^", "^^^ ###", "^^^ ####",
                         "^^^-###", "###-###", "### #^^", "#^^ ###", "#^^ ^##", "##^ ###", "##^ ^##", "##^ ^^#",
                         "^##-##^", "^^^-####", "^## #^^", "^^^ ###", "##^^#", "#^^##", "###^#", "#^###", "^^^ ###",
                         "^^^-####", "^^^####", "###-^^^", "#^^ ###", "^^^ ###", "^^^-####", "###-^^^", "#-#####",
                         "#-####^", "##-#####", "^^^####")
    },
    'person': {
        'first_name': {
            'female': DatasetManager.load_key('names', 'first_name_female'),
            'male':  DatasetManager.load_key('names', 'first_name_male')
        },
        'last_name': DatasetManager.load_key('names', 'last_name'),
        'suffix':   ("Jr.", "Sr.", "II", "III", "IV", "V"),
        'title': ("Mr.", "Mrs.", "Ms.", "Miss", "Mx.", "Dr.", "Prof.", "Rev.", "Fr.", "Sir", "Madam", "Hon.", "Capt.", "Col.", "Maj.", "Lt.", "Sgt.", "Judge", "Pres.", "Gov.", "Amb.", "Engr.", "Atty.")
    },
    'street': {
        'suffix': (
            "Alley", "Avenue", "Bridge", "Brook", "Boulevard", "Bypass", "Circle",
            "Court", "Drive", "Expressway", "Freeway", "Highway", "Lane",
            "Parkway", "Place", "Plaza", "Road", "Square", "Street", "Terrace",
            "Trail", "Way", "Walk", "Loop", "Crescent", "Grove", "Heights"
        ),
        'street_formats': ("{{first_name}} {{street_suffix}}", "{{last_name}} {{street_suffix}}",),
        'building_number_formats': ("#####", "####", "###"),
        'address_formats': ("{{street_number}} {{street_name}}",)
    }
}
