from .dataset_manager import DatasetManager


class LazyKey:
    """Lazily load a dataset key on first access.

    Acts like a sequence (supports __len__ and __getitem__) so callers
    can use random.choice()/len()/iteration transparently.
    """

    def __init__(self, group: str, key: str):
        self.group = group
        self.key = key
        self._val = None

    def _load(self):
        if self._val is None:
            self._val = DatasetManager.load_key(self.group, self.key)
        return self._val

    def __iter__(self):
        return iter(self._load())

    def __len__(self):
        return len(self._load())

    def __getitem__(self, idx):
        return self._load()[idx]

    def __repr__(self):
        return f"LazyKey({self.group!r}, {self.key!r})"

    def __add__(self, other):
        if isinstance(other, LazyKey):
            return tuple(self._load()) + tuple(other._load())
        # allow adding lists/tuples
        try:
            return tuple(self._load()) + tuple(other)
        except Exception:
            return NotImplemented

    def __radd__(self, other):
        if isinstance(other, LazyKey):
            return tuple(other._load()) + tuple(self._load())
        try:
            return tuple(other) + tuple(self._load())
        except Exception:
            return NotImplemented


def L(group: str, key: str) -> LazyKey:
    return LazyKey(group, key)


PAYLOAD = {
    'advanced': {
        'naughty_string': L('advanced', 'naughty_string')
    },
    'ai': {
        "model_type": L('ai', 'model_type'),
        "inference_result": L('ai', 'inference_result'),
        "model_deployment_env": L('ai', 'model_deployment_env'),
        "model_task": L('ai', 'model_task'),
        "model_input_format": L('ai', 'model_input_format'),
        "model_output_format": L('ai', 'model_output_format'),
        "compute_precision": L('ai', 'compute_precision'),
        "model_framework": L('ai', 'model_framework'),
        "model_owner": L('ai', 'model_owner'),
        "retraining_frequency": L('ai', 'retraining_frequency'),
        "concept_drift_status": L('ai', 'concept_drift_status'),
        "model_explainability_method": L('ai', 'model_explainability_method'),
        "model_training_dataset": L('ai', 'model_training_dataset'),
        "model_lifecycle_stage": L('ai', 'model_lifecycle_stage'),
    },
    'basic':  {
        'frequency': L('basic', 'frequency'),
        'nato_phonetic': L('basic', 'nato_phonetic'),
        'emoji': L('emoji', 'emoji'),
        'priority_levels': L('basic', 'priority_levels'),
        'season':  L('basic', 'season'),
        'sentiment': L('basic', 'sentiment'),
        'weather_condition': L('basic', 'weather_condition'),
        'weight_units': L('basic', 'weight_units'),
        "height_units": L('basic', 'height_units'),
        'day_of_week': L('basic', 'day_of_week'),
        'duration_units': L('basic', 'duration_units'),
        'metric_prefixes': L('basic', 'metric_prefixes'),
        'imperial_units': L('basic', 'imperial_units'),
        'month': L('basic', 'month'),
        'paper_size': L('basic', 'paper_size'),
        'punctuation_marks': L('basic', 'punctuation_marks'),
    },
    'car': {
        "vehicle_type":  L('car', 'vehicle_type'),
        "engine_type": L('car', 'engine_type'),
        "fuel_type": L('car', 'fuel_type'),
        "gas_type": L('car', 'gas_type'),
        "transmission_type": L('car', 'transmission_type'),
    },
    'commerce': {
        "product": {
            "category": L('commerce', 'category'),
            "description": L('commerce', 'description'),
            "grocery": L('commerce', 'grocery'),
            'name': L('commerce', 'name'),
            'subcategory': L('commerce', 'subcategory'),
        },
        'stock': {
            'industries': L('commerce', 'stock_industries'),
            'market': L('commerce', 'stock_market')
        },
        'order_status': L('commerce', 'order_status'),
        'payment_method': L('commerce', 'payment_method'),
        'restaurant_type': L('commerce', 'restaurant_type'),
        'review_text': L('commerce', 'review_text'),
        'shipping_method': L('commerce', 'shipping_method'),
        'subscription_plan': L('commerce', 'subscription_plan'),
        'coffee_type': L('commerce', 'coffee_type'),
        'delivery_status': L('commerce', 'delivery_status'),
        'fabric_type': L('commerce', 'fabric_type'),
        'furniture_type': L('commerce', 'furniture_type'),
        'gem_stone': L('commerce', 'gem_stone'),
        'ingredient': L('commerce', 'ingredient'),
        'inventory_status': L('commerce', 'inventory_status'),
        'loyalty_tier': L('commerce', 'loyalty_tier'),
        'meal_type': L('commerce', 'meal_type'),
        'membership_level': L('commerce', 'membership_level'),
        'office_supply': L('commerce', 'office_supply'),
        'payment_status': L('commerce', 'payment_status'),
        'postal_service': L('commerce', 'postal_service'),
        'recipe_name': L('commerce', 'recipe_name'),
        'sales_channel': L('commerce', 'sales_channel'),
        'warranty_period': L('commerce', 'warranty_period'),
        'water_type': L('commerce', 'water_type'),
        'return_reason': L('commerce', 'return_reason'),
        'bundle_type': L('commerce', 'bundle_type'),
        "price_sensitivity_level": L('commerce', 'price_sensitivity_level'),
        "freight_mode": L('commerce', 'freight_mode'),
        "recommendation_slot_position":  L('commerce', 'recommendation_slot_position'),
    },
    'communication': {
        'latency_range': {
            "2G": (150, 1000),
            "2G EDGE": (200, 800),
            "3G": (100, 500),
            "3G HSPA": (80, 400),
            "4G LTE": (20, 100),
            "4G LTE-A": (15, 80),
            "5G": (5, 50),
            "5G NSA": (5, 40),
            "5G SA": (3, 20),
            "Wi-Fi 2.4GHz": (2, 60),
            "Wi-Fi 5GHz": (1, 30),
            "Wi-Fi 6": (1, 15),
            "Satellite": (500, 1500),
            "Satellite LEO": (50, 100),
            "DSL": (10, 100),
            "Fiber": (1, 20),
        },
        "bluetooth_version": L('communication', 'bluetooth_version'),
        "upload_speed": L('communication', 'upload_speed'),
        "download_speed": L('communication', 'download_speed'),
        "sim_card_type": L('communication', 'sim_card_type'),
        "mobile_carrier": L('communication', 'mobile_carrier'),
        "data_plan": L('communication', 'data_plan'),
        "wifi_standard": L('communication', 'wifi_standard'),
        "wifi_band": L('communication', 'wifi_band'),
        "nfc_support": L('communication', 'nfc_support'),
        "hotspot_capability": L('communication', 'hotspot_capability'),
        "roaming_status": L('communication', 'roaming_status'),
        "carrier_lock_status": L('communication', 'carrier_lock_status'),
        "volte_support": L('communication', 'volte_support'),
        "wifi_calling_support": L('communication', 'wifi_calling_support'),
        "dual_sim_capability": L('communication', 'dual_sim_capability'),
        "apn_settings": L('communication', 'apn_settings'),
        "call_quality_rating": L('communication', 'call_quality_rating'),
    },
    'construction': {
        "heavy_equipment": L('construction', 'heavy_equipment'),
        "materials":  L('construction', 'materials'),
        "roles": L('construction', 'roles'),
        "subcontracts": L('construction', 'subcontracts'),
        'trades': L('construction', 'trades'),
        "building_type": L('construction', 'building_type'),
        "material_type": L('construction', 'material_type'),
        "tool_type": L('construction', 'tool_type'),
    },
    'crypto': {
        "wallet": L('crypto', 'wallet')
    },
    'education': {
        "academic_subject": L('education', 'academic_subject'),
        "attendance_status": L('education', 'attendance_status'),
        "certification": L('education', 'certification'),
        "college_major": L('education', 'college_major'),
        "elearning_platform": L('education', 'e_learning_platform'),
        "qualification": L('education', 'qualification'),
        "school_type": L('education', 'school_type'),
        "semester": L('education', 'semester')
    },
    'finance': {
        "loan_type": L('finance', 'loan_type'),
        "asset_type": L('finance', 'asset_type'),
        "expense_category": L('finance', 'expense_category'),
        "grant_type": L('finance', 'grant_type'),
        "insurance_provider": L('finance', 'insurance_provider'),
        "insurance_type": L('finance', 'insurance_type'),
        "investment_strategy": L('finance', 'investment_strategy'),
        "payment_term": L('finance', 'payment_term'),
        "risk_level": L('finance', 'risk_level'),
        "tax_type": L('finance', 'tax_type'),
        "transaction_type": L('finance', 'transaction_type'),
        "spending_behavior": L('finance', 'spending_behavior'),
        "investment_persona": L('finance', 'investment_persona'),
        "transaction_pattern": L('finance', 'transaction_pattern'),
        "financial_goal": L('finance', 'financial_goal'),
        "account_type": L('finance', 'account_type'),
        "transfer_channel": L('finance', 'transfer_channel'),
        "aml_risk_category": L('finance', 'aml_risk_category'),
        "spending_category": L('finance', 'spending_category'),
        "savings_goal": L('finance', 'savings_goal'),
        "credit_score_band": L('finance', 'credit_score_band'),
        "kyc_status": L('finance', 'kyc_status'),
        "wealth_segment": L('finance', 'wealth_segment'),
    },
    'gaming': {
        "badge": L('gaming', 'badge'),
        "avatar_class": L('gaming', 'avatar_class'),
        "skill_level": L('gaming', 'skill_level'),
        "match_result": L('gaming', 'match_result'),
        "player_role": L('gaming', 'player_role'),
        "guild_name": L('gaming', 'guild_name'),
        "achievement_title": L('gaming', 'achievement_title'),
        "session_outcome": L('gaming', 'session_outcome'),
    },
    'health': {
        "blood_type": L('health', 'blood_type'),
        "disease_name": L('health', 'disease_name'),
        "medication_dosage": L('health', 'medication_dosage'),
        "vitamin": L('health', 'vitamin'),
        "allergy": L('health', 'allergy'),
        "body_part": L('health', 'body_part'),
        "chromosome": L('health', 'chromosome'),
        "dietary_restriction": L('health', 'dietary_restriction'),
        "disability_type": L('health', 'disability_type'),
        "emergency_type": L('health', 'emergency_type'),
        "exercise_type": L('health', 'exercise_type'),
        "health_insurance_plan": L('health', 'health_insurance_plan'),
        "hormone":  L('health', 'hormone'),
        "hospital_department": L('health', 'hospital_department'),
        "lab_test": L('health', 'lab_test'),
        "macro_nutrient": L('health', 'macro_nutrient'),
        "medical_specialty": L('health', 'medical_specialty'),
        "mental_health_condition": L('health', 'mental_health_condition'),
        "nutrient": L('health', 'nutrient'),
        "organ":  L('health', 'organ'),
        "pharmacy_name": L('health', 'pharmacy_name'),
        "symptom": L('health', 'symptom'),
        "workout_duration": ("15 minutes", "30 minutes", "45 minutes", "90 minutes", "1 hour", "2 hour", "3 Hour"),
        "vaccination_type": L('health', 'vaccination_type'),
        "diet_type": L('health', 'diet_type'),
        "blood_pressure_category": L('health', 'blood_pressure_category'),
        "allergy_flag": L('health', 'allergy_flag'),
        "appointment_status": L('health', 'appointment_status'),
        "lab_test_type": L('health', 'lab_test_type'),
        "triage_level": L('health', 'triage_level'),
    },
    'it': {
        'domains': L('it', 'domains'),
        'mime_types': {
            "application": ("application/atom+xml", "application/ecmascript", "application/EDI-X12", "application/EDIFACT", "application/json", "application/javascript",
                            "application/octet-stream", "application/ogg", "application/pdf", "application/postscript", "application/rdf+xml", "application/rss+xml",
                            "application/soap+xml", "application/font-woff", "application/xhtml+xml", "application/xml-dtd", "application/xop+xml", "application/zip", "application/gzip"),
            "audio": ("audio/basic", "audio/L24", "audio/mp4", "audio/mpeg", "audio/ogg", "audio/vorbis", "audio/vnd.rn-realaudio", "audio/vnd.wave", "audio/webm"),
            "image": ("image/gif", "image/jpeg", "image/pjpeg", "image/png", "image/svg+xml", "image/tiff", "image/vnd.microsoft.icon"),
            "message": ("message/http", "message/imdn+xml", "message/partial", "message/rfc822"),
            "model": ("model/example", "model/iges", "model/mesh", "model/vrml", "model/x3d+binary", "model/x3d+vrml", "model/x3d+xml"),
            "multipart": ("multipart/mixed", "multipart/alternative", "multipart/related", "multipart/form-data", "multipart/signed", "multipart/encrypted"),
            "text": ("text/cmd", "text/css", "text/csv", "text/html", "text/javascript", "text/plain", "text/vcard", "text/xml"),
            "video": ("video/mpeg", "video/mp4", "video/ogg", "video/quicktime", "video/webm", "video/x-matroska", "video/x-ms-wmv", "video/x-flv"),
        },
        'user_agents': L('it', 'user_agents'),
        'tlds': (".com", ".org", ".net", ".io", ".co", ".edu", ".gov", ".mil", ".us", ".uk", ".ca", ".au", ".de", ".fr", ".jp", ".sg", ".ph", ".in", ".cn", ".br",
                         ".za", ".es", ".it", ".nl", ".se", ".no", ".ch", ".biz", ".info", ".xyz", ".online", ".site", ".tech", ".store", ".ai", ".app", ".dev", ".cloud", ".me", ".tv"),
        'prefix': ("sk-", "api_", "key-", "ghp_", "tok_", "auth_"),
        'browsers': (("Google Chrome", "130.0.6723.69"),
                     ("Mozilla Firefox", "132.0"),
                     ("Microsoft Edge", "130.0.2849.56"),
                     ("Safari", "18.0"),
                     ("Opera", "105.0.4985.64"),
                     ("Brave", "1.73.113"),
                     ("Vivaldi", "6.7.3329.25"),
                     ("Samsung Internet", "25.0.1.3"),
                     ("UC Browser", "15.1.0.1225"),
                     ("DuckDuckGo Browser", "1.100.2"),
                     ("Tor Browser", "13.0.4"),
                     ("QQ Browser", "15.2.0.0"),
                     ("Yandex Browser", "24.9.1.822"),
                     ("Puffin Browser", "9.10.2.51548"),
                     ("Maxthon", "7.1.8.9000")),
        'cloud_provider': L('it', 'cloud_provider'),
        'database_type': L('it', 'database_type'),
        'cloud_storage_service': L('it', 'cloud_storage_service'),
        'docker_images': L('it', 'docker_images'),
        'error_messages': L('it', 'error_messages'),
        'file_size_units': ("B", "KB", "MB", "GB", "TB"),
        'font_family': L('it', 'font_family'),
        'http_method': ("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"),
        'http_standard_code': L('it', 'http_standard_code'),
        'iot_device_type': L('it', 'iot_device_type'),
        'operating_system': L('it', 'operating_system'),
        'port_number': L('it', 'port_number'),
        'programming_language': L('it', 'programming_language'),
        'security_question': L('it', 'security_question'),
        "wifi_ssid": L('it', 'wifi_ssid'),
        "app_store_category": L('it', 'app_store_category'),
        "cookie_name": L('it', 'cookie_name'),
        'css_color': L('it', 'css_color'),
        'data_centers': L('it', 'data_centers'),
        'dns_record_type': L('it', 'dns_record_type'),
        'document_type': L('it', 'document_type'),
        'electrical_component': L('it', 'electrical_component'),
        'encryption_algorithm': L('it', 'encryption_algorithm'),
        'form_factor': L('it', 'form_factor'),
        'framework': L('it', 'framework'),
        'hardware':  L('it', 'hardware'),
        'incident_type': L('it', 'incident_type'),
        'keyboard_layout': L('it', 'keyboard_layout'),
        'laptop_brand':  L('it', 'laptop_brand'),
        'license_type': L('it', 'license_type'),
        'memory_size':  L('it', 'memory_size'),
        'microservice_name':  L('it', 'microservice_name'),
        'network_protocol': L('it', 'network_protocol'),
        'notification_type': L('it', 'notification_type'),
        'package_manager': L('it', 'package_manager'),
        'password_strength': L('it', 'password_strength'),
        'permission_level': L('it', 'permission_level'),
        'power_source': L('it', 'power_source'),
        'printer_type': L('it', 'printer_type'),
        'protocol_version': L('it', 'protocol_version'),
        'screen_resolution': L('it', 'screen_resolution'),
        "screen_size": L('it', 'screen_size'),
        "social_media_platform": L('it', 'social_media_platform'),
        "software_license": L('it', 'software_license'),
        "storage_type": L('it', 'storage_type'),
        "subject_line": L('it', 'subject_line'),
        "technology_stack": L('it', 'technology_stack'),
        "ticket_priority": L('it', 'ticket_priority'),
        "uptime_percentage": L('it', 'uptime_percentage'),
        "api_endpoint_path": L('it', 'api_endpoint_path'),
        "log_level": L('it', 'log_level'),
        "server_name": L('it', 'server_name'),
        "sensor_type":  L('it', 'sensor_type'),
        "device_location":  L('it', 'device_location'),
        "power_state":  L('it', 'power_state'),
        "smart_device_brand": L('it', 'smart_device_brand'),
        "smart_device_type":  L('it', 'smart_device_type'),
        "automation_trigger":  L('it', 'automation_trigger'),
        "automation_action":  L('it', 'automation_action'),
        "energy_mode":  L('it', 'energy_mode'),
        "feature_usage_event":  L('it', 'feature_usage_event'),
        "subscription_renewal_status": L('it', 'subscription_renewal_status'),
        "engagement_level": L('it', 'engagement_level'),

    },
    'legal': {
        'crime': L('legal', 'crime'),
        "law_type": L('legal', 'law_type'),
        "court_level": L('legal', 'court_level'),
        "legislation_status": L('legal', 'legislation_status'),
        "legal_jurisdiction": L('legal', 'legal_jurisdiction'),
        "evidence_type": L('legal', 'evidence_type'),
        "legal_representation": L('legal', 'legal_representation'),
        "verdict": L('legal', 'verdict'),
        "penalty_type": L('legal', 'penalty_type'),
        "appeal_status": L('legal', 'appeal_status'),
        "contract_type": L('legal', 'contract_type'),
        "notary_status": L('legal', 'notary_status'),
        "legal_compliance_status": L('legal', 'legal_compliance_status'),
        "regulatory_agency": L('legal', 'regulatory_agency'),
        "legal_filing_type": L('legal', 'legal_filing_type'),
        "legal_fee_category": L('legal', 'legal_fee_category'),
        "bail_status": L('legal', 'bail_status'),
    },
    'location': {
        "timezone_abbreviation": L('location', 'timezone_abbreviation'),
        "compass_direction": L('location', 'compass_direction'),
        "continent": L('location', 'continent'),
        "facility_type": L('location', 'facility_type'),
        "federal_holiday": L('location', 'federal_holiday'),
        "floor_number": L('location', 'floor_number'),
        "holiday": L('location', 'holiday'),
        "home_type": L('location', 'home_type'),
        "property_type": L('location', 'property_type'),
        "road_type": L('location', 'road_type'),
        "venue_type": L('location', 'venue_type'),
        "geo_zone": L('location', 'venue_type'),
        "street_type": L('location', 'street_type'),
        "traffic_flow_level": L('location', 'traffic_flow_level'),
        "urban_land_use": L('location', 'urban_land_use'),
        "public_service_request_type": L('location', 'public_service_request_type'),
    },
    'marketing': {
        'campaign_name': L('marketing', 'campaign_name'),
        "recommendation_reason": L('marketing', 'recommendation_reason'),
        "next_best_action":  L('marketing', 'next_best_action'),
        "user_preference_tag": L('marketing', 'user_preference_tag'),
        "promotion_type":  L('marketing', 'promotion_type'),
        "customer_segment":  L('marketing', 'customer_segment'),
        "channel_source":  L('marketing', 'channel_source'),
        "conversion_status": L('marketing', 'conversion_status'),
        "churn_risk":  L('marketing', 'churn_risk'),
        "preferred_communication_channel": L('marketing', 'preferred_communication_channel'),
        "recent_search_term":  L('marketing', 'recent_search_term'),
        "cart_abandonment_status":  L('marketing', 'cart_abandonment_status'),
        "cross_sell_opportunity": L('marketing', 'cross_sell_opportunity'),
        "upsell_opportunity": L('marketing', 'upsell_opportunity'),
        "sms_response_status": L('marketing', 'sms_response_status'),
        "coupon_usage_status": L('marketing', 'coupon_usage_status'),
        "referral_source":  L('marketing', 'referral_source'),
        "influencer_attribution": L('marketing', 'influencer_attribution'),
        "preferred_product_category":  L('marketing', 'preferred_product_category'),
        "seasonal_interest":  L('marketing', 'seasonal_interest'),
        "price_sensitivity":  L('marketing', 'price_sensitivity'),
        "customer_mood_intent": L('marketing', 'customer_mood_intent'),
    },
    'nature': {
        "planet": L('nature', 'planet'),
        "biome": L('nature', 'biome'),
        "bird_species": L('nature', 'bird_species'),
        "constellation":  L('nature', 'constellation'),
        "dog_breed":  L('nature', 'dog_breed'),
        "ecosystem":  L('nature', 'ecosystem'),
        "element_state": L('nature', 'element_state'),
        "energy_source":  L('nature', 'energy_source'),
        "environmental_issue":  L('nature', 'environmental_issue'),
        "fish_species": L('nature', 'fish_species'),
        "flower_type":  L('nature', 'flower_type'),
        "insect_species": L('nature', 'insect_species'),
        "moon_phase":  L('nature', 'moon_phase'),
        "ocean": L('nature', 'ocean'),
        "particle":  L('nature', 'particle'),
        "precipitation_type":  L('nature', 'precipitation_type'),
        "satellite": L('nature', 'satellite'),
        "species":  L('nature', 'species'),
        "tree_species": L('nature', 'tree_species'),
        "wind_direction": L('nature', 'wind_direction'),
        "animal_habitat": L('nature', 'animal_habitat'),
        "geological_formation": L('nature', 'geological_formation'),
        "climate_zone": L('nature', 'climate_zone'),
        "natural_resource":  L('nature', 'natural_resource'),
        "vegetation_type": L('nature', 'vegetation_type'),
        'hazard_risk_zone': L('nature', 'hazard_risk_zone'),
        'air_quality_category': L('nature', 'air_quality_category'),
    },
    'personal': {
        'race': L('personal', 'race'),
        'gender': {
            'facebook': L('personal', 'gender_facebook'),
            'main': ('Male', 'Female', 'Non-binary', 'Genderqueer', 'Genderfluid', 'Bigender', 'Agender'),
            'abbrev': ('M', 'F'),
            'binary': ('Male', 'Female')
        },
        'job':  L('misc', 'job'),
        'shirt_sizes': ("XS", "S", "M", "L", "XL", "XXL", "XXXL"),
        'buzzword': L('personal', 'buzzword'),
        'nationality': L('personal', 'nationality'),
        'quote': L('quote', 'quotes'),
        "business_type": L('personal', 'business_type'),
        "degree": L('personal', 'degree'),
        "education_level": L('personal', 'education_level'),
        "employment_status": L('personal', 'employment_status'),
        "hobby":  L('personal', 'hobby'),
        "industry": L('personal', 'industry'),
        "marital_status": L('personal', 'marital_status'),
        "military_rank": L('personal', 'military_rank'),
        "mood":  L('personal', 'mood'),
        "pronoun": L('personal', 'pronoun'),
        "religion": L('personal', 'religion'),
        "team_name": L('personal', 'team_name'),
        "zodiac_sign": L('personal', 'zodiac_sign'),
        "age_group": L('personal', 'age_group'),
        "conference_name": L('personal', 'conference_name'),
        "event_type":  L('personal', 'event_type'),
        "hair_color":  L('personal', 'hair_color'),
        "income_level":  L('personal', 'income_level'),
        "interview_stage": L('personal', 'interview_stage'),
        "legal_entity": L('personal', 'legal_entity'),
        "life_stage": L('personal', 'life_stage'),
        "occupation": L('misc', 'job'),
        "organization_type": L('personal', 'organization_type'),
        "performance_rating":  L('personal', 'performance_rating'),
        "pet_type": L('personal', 'pet_type'),
        "project_status":  L('personal', 'project_status'),
        "reaction": L('personal', 'reaction'),
        "relationship_type": L('personal', 'relationship_type'),
        "role": L('personal', 'role'),
        "daily_habit": L('personal', 'daily_habit'),
        "personality_trait":  L('personal', 'personality_trait'),
    },
    'political': {
        'election_type': L('political', 'election_Type'),
        "political_ideology": L('political', 'political_ideology'),
        "political_party": L('political', 'political_party'),
        "party_affiliation_strength": L('political', 'party_affiliation_strength'),
        "government_branch": L('political', 'government_branch'),
        "head_of_state": L('political', 'head_of_state'),
        "head_of_government": L('political', 'head_of_government'),
        "cabinet_position": L('political', 'cabinet_position'),
        "voter_eligibility": L('political', 'voter_eligibility'),
        "campaign_funding_source": L('political', 'campaign_funding_source'),
        "lobbying_influence_level": L('political', 'lobbying_influence_level'),
        "policy_domain": L('political', 'policy_domain'),
        "diplomatic_relationship": L('political', 'diplomatic_relationship'),
        "treaty_type": L('political', 'treaty_type'),
        "sanction_type": L('political', 'sanction_type'),
        "border_control_status": L('political', 'border_control_status'),
        "military_alliance": L('political', 'military_alliance'),
        "geopolitical_region": L('political', 'geopolitical_region'),
    },
    'products': {
        "podcast_name": L('products', 'podcast_name'),
        "streaming_service": L('products', 'streaming_service'),
        "award_name": L('products', 'award_name'),
        "broadcast_network": L('products', 'broadcast_network'),
        "content_rating": L('products', 'content_rating'),
        "guitar_type": L('products', 'guitar_type'),
        "magazine_title": L('products', 'magazine_title'),
        "media_format": L('products', 'media_format'),
        "musical_genre": L('products', 'musical_genre'),
        "musical_instrument": L('products', 'musical_instrument'),
        "news_category": L('products', 'news_category'),
        "parental_rating": L('products', 'parental_rating'),
        "record_label": L('products', 'record_label'),
        "sound_effect": L('products', 'sound_effect'),
        "supernatural_creature": L('products', 'supernatural_creature'),
        "video_format": L('products', 'video_format'),
        "video_quality": L('products', 'video_quality'),
        "stock_reorder_flag": L('products', 'stock_reorder_flag'),
        "shelf_location": L('products', 'shelf_location'),
        "product_grade": L('products', 'product_grade'),
        "demand_forecast": L('products', 'demand_forecast'),
        "supplier_contract": L('products', 'supplier_contract'),
    },
    'sports': {
        'olympic': L('sports', 'olympic'),
        "equipment_type": L('sports', 'equipment_type'),
        "league": L('sports', 'league'),
        "stadium_name": L('sports', 'stadium_name'),
    },
    'travel': {
        "flight_status": L('travel', 'flight_status'),
        "room_type": L('travel', 'room_type'),
        "amenity": L('travel', 'amenity'),
        "bed_size": L('travel', 'bed_size'),
        "parking_type": L('travel', 'parking_type'),
        "ticket_type": L('travel', 'ticket_type'),
        "transport_mode": L('travel', 'transport_mode'),
    },


    'departments': {
        'corporate':  L('misc', 'corporate'),
        'retail': L('misc', 'retail'),
    },
    'file': {
        "image":  L('file', 'image'),
        "audio": L('file', 'audio'),
        "video": L('file', 'video'),
        "text": L('file', 'text'),
        "office": L('file', 'office'),
        "archive": L('file', 'archive'),
        "executable": L('file', 'executable'),
        "data": L('file', 'data'),
        "code": L('file', 'code'),
        "font": L('file', 'font'),
        "system": L('file', 'system'),
        "design": L('file', 'design'),
        "backup": L('file', 'backup'),
    },
    'format': {
        'company': ("{{last_name}} {{company_suffix}}", "{{last_name}}-{{last_name}}", "{{last_name}}, {{last_name}} and {{last_name}}",),
        'username':  ("{{first_name}}.{{last_name}}", "{{last_name}}.{{first_name}}", "{{first_name}}_{{last_name}}",
                      "{{first_name}}-{{last_name}}", "{{first_name}}{{last_name}}", "{{first_name}}.{{last_name}}@",
                      "{{first_name}}.{{last_name}}##", "{{first_name}}_{{last_name}}@", "{{first_name}}_{{last_name}}_##",
                      "{{first_name}}##",  "{{last_name}}##",  "@{{first_name}}_{{last_name}}",  "{{first_name}}_@{{last_name}}",
                      "{{first_name}}##@{{last_name}}",  "{{first_name}}_{{last_name}}_@", "{{first_name}}-{{last_name}}##",
                      "{{first_name}}.{{last_name}}_@", "{{first_name}}##.{{last_name}}", "{{last_name}}_{{first_name}}##"),
        'email': (
            "{{user_name}}@{{domain_name}}",
            "{{first_name}}.{{last_name}}@{{domain_name}}",
            "{{first_name}}{{last_name}}@{{domain_name}}",
            "{{first_name}}_{{last_name}}@{{domain_name}}",
            "{{first_name}}.{{last_name}}+{{number}}@{{domain_name}}",
            "{{first_name}}@{{subdomain}}.{{domain_name}}",
        ),
        'plate_number': ("#^^####", "##^^###", "### ^^^", "####", "^^^####", "### ^^^", "###^^^", "#^^^###",
                         "###-^^^", "^^^-###", "###-^^^", "######", "^^-####", "^^^ ^##", "### ^^^", "^## #^^",
                         "### #^^", "^^^####", "^^ ####", "^^^ ###", "H^^ ###", "Z^^ ###", "K^^ ###", "L^^ ###",
                         "M^^ ###", "^ ######", "#^ #####", "#^ ^####", "#^ ^^^###", "#^ ####^", "##^ ####",
                         "^^ #####", "^^# ####", "###^", "###^^", "###^^^", "^^^ ###", "### ^^^", "### ^^^",
                         "### ^^^", "#### ^^", "#^^####", "#^^^ ##", "#^^ ###", "### ^^#", "##^ ^##", "### ^^^",
                         "#^^ ^##", "###-^^^", "^^^ ###", "^^# ^#^", "#-#####^", "##-####^", "^^^ ###", "#-^####",
                         "##-^###", "##-^^##", "##^-###", "### ####", "^##-^^^", "###-^^^", "^^^-###", "^^^-####",
                         "###-^^^^", "### ^^^", "^^^ ###", "^^^ ####", "^^^-###", "### ^^^", "^^^ ###", "^^^ ####",
                         "^^^-###", "###-###", "### #^^", "#^^ ###", "#^^ ^##", "##^ ###", "##^ ^##", "##^ ^^#",
                         "^##-##^", "^^^-####", "^## #^^", "^^^ ###", "##^^#", "#^^##", "###^#", "#^###", "^^^ ###",
                         "^^^-####", "^^^####", "###-^^^", "#^^ ###", "^^^ ###", "^^^-####", "###-^^^", "#-#####",
                         "#-####^", "##-#####", "^^^####")
    },
    'person': {
        'first_name': {
            'female': L('names', 'first_name_female'),
            'male':  L('names', 'first_name_male')
        },
        'last_name': L('names', 'last_name'),
        'suffix':   ("Jr.", "Sr.", "II", "III", "IV", "V"),
        'title': ("Mr.", "Mrs.", "Ms.", "Miss", "Mx.", "Dr.", "Prof.", "Rev.", "Fr.", "Sir", "Madam", "Hon.", "Capt.", "Col.", "Maj.", "Lt.", "Sgt.", "Judge", "Pres.", "Gov.", "Amb.", "Engr.", "Atty.")
    },
    'street': {
        'suffix': (
            "Alley", "Avenue", "Bridge", "Brook", "Boulevard", "Bypass", "Circle",
            "Court", "Drive", "Expressway", "Freeway", "Highway", "Lane",
            "Parkway", "Place", "Plaza", "Road", "Square", "Street", "Terrace",
            "Trail", "Way", "Walk", "Loop", "Crescent", "Grove", "Heights"
        ),
        'street_formats': ("{{first_name}} {{street_suffix}}", "{{last_name}} {{street_suffix}}",),
        'building_number_formats': ("#####", "####", "###"),
        'address_formats': ("{{street_number}} {{street_name}}",)
    }
}
